name: rl_env2
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - matplotlib
  - pandas
  - pip
  - pip:
      - stable-baselines3
      - gym
      - shimmy
      - procgen
      - pygame
      - python-dotenv
      # - pytorch
      # - torchvision
      # - torchaudio
