# Model related parameters
seed: 49
batch_size: 4
buffer_mult: 8
lr: 0.00025
iterations_per_weight_update: 256
training_steps: 100000
l1_coeff: 2
beta1: 0.9
beta2: 0.999
dict_size: 64
device: cuda:0
model_batch_size: 4
d_in: 2048
log_every: 100
save_every: 1000
states_provided: False
hook_point: blocks.14.hook_resid_pre
hf_token: YOUR_HUGGINGFACE_TOKEN
wandb_project: YOUR_WANDB_PROJECT
wandb_entity: YOUR_WANDB_ENTITY
