# Model related parameters
seed: 49
batch_size: 4 # timesteps?
buffer_mult: 8 # batch_size * = buffer
lr: 0.00025
iterations_per_weight_update: 256
training_steps: 100000
l1_coeff: 2
beta1: 0.9
beta2: 0.999
dict_size: 64
device: cuda:0
model_batch_size: 4
d_in: 2048
log_every: 100
save_every: 1000
states_provided: False
hook_point: blocks.14.hook_resid_pre
hf_token: INSERT
wandb_project: INSERT
wandb_entity: INSERT
model_a_path: /storage/coda1/p-adelarue3/0/shared/v3/checkpoints/00001
model_b_path: /storage/coda1/p-adelarue3/0/shared/v3/checkpoints/00060
